1//
CREATE TABLE TEAM
(
    TEAM_ID VARCHAR2(15),
    NAME VARCHAR2(50) NOT NULL ,
    BUDGET INT
);


CREATE TABLE DRIVER
(
    DRIVER_NO VARCHAR2(50) PRIMARY KEY,
    DRIVER_NAME VARCHAR2(100) NOT NULL ,
    DRIVER_CITY VARCHAR2(100)
);


2// 


INSERT INTO TEAM (TEAM_ID, NAME, BUDGET)
VALUES ('1', 'Ferrari', 120000.00);

INSERT INTO TEAM (TEAM_ID, NAME, BUDGET)
VALUES ('2', 'Redbull',200000.50);

INSERT INTO TEAM (TEAM_ID, NAME, BUDGET)
VALUES ('3', 'McLaren',100000.00);

INSERT INTO TEAM (TEAM_ID, NAME, BUDGET)
VALUES ('4', 'Mercedes',93000.70);


INSERT INTO DRIVER VALUES ('C-101', 'Max', 'Amsterdam');
INSERT INTO DRIVER VALUES ('C-102', 'Piastri', 'Melbourne');
INSERT INTO DRIVER VALUES ('C-103', 'Norris', 'Bristol');
INSERT INTO DRIVER VALUES ('C-104', 'Leclerc', 'Monte Carlo');
INSERT INTO DRIVER VALUES ('C-105', 'Hamilton', 'Bristol');


3// 


ALTER TABLE DRIVER ADD DATE_OF_BIRTH DATE;


ALTER TABLE DRIVER RENAME COLUMN DRIVER_NO TO DRIVER_ID;


ALTER TABLE TEAM ADD TEAM_ID PRIMARY KEY;


4//

SELECT BUDGET FROM TEAM 
WHERE BUDGET > 120000;

SELECT DRIVER_NAME FROM DRIVER 
WHERE DRIVER_CITY != 'Bristol';

UPDATE DRIVER 
SET DRIVER_CITY = 'Sydney' 
WHERE DRIVER_NO = 'C-101';


UPDATE TEAM 
SET  BUDGET = BUDGET - 0.25*BUDGET
WHERE BUDGET >  100000;


UPDATE TEAM BUDGET 
SET BUDGET = BUDGET - 20000
WHERE  TEAM_ID  = '3';

UPDATE TEAM BUDGET 
SET BUDGET = BUDGET + 20000
WHERE  TEAM_ID  = '2';


5//
DELETE FROM TEAM 
WHERE BUDGET < 93000.70;

DROP TABLE TEAM;

DROP TABLE DRIVER;






