--1
CREATE USER 220041158 IDENTIFIED BY cse4308;
GRANT CREATE SESSION, RESOURCE TO 220041158;

--2
CREATE TABLE STUDENT (
ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
DEPT_NAME CHAR(3),
TOT_CRED INT
);



--3

INSERT INTO STUDENT VALUES (128,'Zhang','CSE',102);
INSERT INTO STUDENT VALUES (12345,'Shankar','CSE',32);
INSERT INTO STUDENT VALUES (19991,'Brandt','HIS',80);
INSERT INTO STUDENT VALUES (23121,'Chavez','FIN',110);
INSERT INTO STUDENT VALUES (44553,'Peltier','PHY',56);
INSERT INTO STUDENT VALUES (45678,'Levy','PHY',46);
INSERT INTO STUDENT VALUES (54321,'Williams','CSE',5);
INSERT INTO STUDENT VALUES (55739,'Sanchez','MUS',38);
INSERT INTO STUDENT VALUES (70557,'Snow','PHY',0);
INSERT INTO STUDENT VALUES (76543,'Brown','CSE',58);
INSERT INTO STUDENT VALUES (76653,'Aoi','EEE',60);
INSERT INTO STUDENT VALUES (98765,'Bourikas','EEE',9);
INSERT INTO STUDENT VALUES (98988,'Tanaka','BIO',120);


--4

SELECT *FROM STUDENT;

SELECT NAME,DEPT_NAME FROM STUDENT 
WHERE TOT_CRED>80 AND TOT_CRED<120;

SELECT ID, NAME FROM STUDENT 
WHERE DEPT_NAME = 'CSE';

SELECT NAME,TOT_CRED FROM STUDENT 
WHERE DEPT_NAME = 'PHY' AND TOT_CRED<50;

SELECT DEPT_NAME FROM STUDENT 
WHERE NAME ='Shankar' AND NAME='Sanchez';


--5

DELETE FROM STUDENT 
WHERE TOT_CRED < 10;

--6 

DROP TABLE STUDENT;





