--1


--2 
SELECT FIRST_NAME , COUNT(*) as Count_Name FROM ARTIST GROUP BY FIRST_NAME HAVING COUNT(*) > 1;


--3

SELECT a.TITLE FROM ALBUM a LEFT JOIN SONG s on a.ALB_ID = s.SONG_ID WHERE s.SONG_ID IS NULL; 


--4

SELECT RELEASE_YEAR , COUNT(*) as count_song FROM ALBUM GROUP BY RELEASE_YEAR ORDER BY count_song;


--5
SELECT MAX(RELEASE_YEAR) - MIN(RELEASE_YEAR) FROM ALBUM;

--6
SELECT a.FIRST_NAME FROM ARTIST a JOIN PERFORMS P ON a.ART_ID = P.ART_ID JOIN RATING R ON P.SONG_ID = R.SONG_ID WHERE R.RATING = (SELECT MAX(RATING) FROM RATING);

--7 

SELECT SUM(RATING) FROM RATING GROUP BY SONG_ID ORDER BY SUM(RATING) DESC;


-- 8


SELECT TITLE, AVG_RATING, NUM_LISTENERS FROM (SELECT S.TITLE, MIN(R.RATING) AS AVG_RATING, COUNT(R.LIS_ID) AS NUM_LISTENERS FROM RATING R JOIN SONG S ON R.SONG_ID = S.SONG_ID GROUP BY S.SONG_ID, S.TITLE HAVING COUNT(R.LIS_ID) >= 2  ORDER BY MIN(R.RATING) ASC  ) WHERE ROWNUM = 1;


--9

SELECT * FROM (SELECT A.FIRST_NAME || ' ' || A.LAST_NAME AS ARTIST_NAME, COUNT(P.SONG_ID) AS SONG_COUNT FROM ARTIST A JOIN PERFORMS P ON A.ART_ID = P.ART_ID JOIN INCLUDES I ON P.SONG_ID = I.SONG_ID JOIN ALBUM AL ON I.ALB_ID = AL.ALB_ID WHERE AL.RELEASE_YEAR < 2015 GROUP BY A.ART_ID, A.FIRST_NAME, A.LAST_NAME ORDER BY SONG_COUNT DESC) WHERE ROWNUM = 1;  


--10

SELECT ARTIST_NAME, GENDER, AVG_RATING
FROM (
    SELECT A.FIRST_NAME || ' ' || A.LAST_NAME AS ARTIST_NAME, 
           A.GENDER, 
           AVG(R.RATING) AS AVG_RATING
    FROM ARTIST A
    JOIN PERFORMS P ON A.ART_ID = P.ART_ID
    JOIN RATING R ON P.SONG_ID = R.SONG_ID
    GROUP BY A.ART_ID, A.FIRST_NAME, A.LAST_NAME, A.GENDER
    ORDER BY A.GENDER, AVG(R.RATING) DESC
) WHERE ROWNUM <= 2; 








