--1


--2 
SELECT FIRST_NAME , COUNT(*) as Count_Name
FROM ARTIST
GROUP BY FIRST_NAME
HAVING COUNT(*) > 1;


--3
SELECT a.TITLE 
FROM ALBUM a 
LEFT JOIN SONG s on a.ALB_ID = s.SONG_ID
WHERE s.SONG_ID IS NULL; 


--4
SELECT RELEASE_YEAR , COUNT(*) as count_song
FROM ALBUM 
GROUP BY RELEASE_YEAR
ORDER BY count_song;

--5
SELECT MAX(RELEASE_YEAR) - MIN(RELEASE_YEAR) 
FROM ALBUM;

--6
SELECT a.FIRST_NAME, avg(RATING) as AVERAGE_RATING 
FROM ARTIST a;
--JOIN SONG s on a.ART_ID = s.SONG_ID
--JOIN RATING r on s.SONG_ID = r.SONG_ID

--JOIN RATING r on a.ART_ID = r.SONG_ID
--GROUP BY a.FIRST_NAME
--ORDER BY AVERAGE_RATING DESC;










